import React from 'react';

const chartLoaderSVG =
  'data:image/svg+xml;base64,' +
  'PHN2ZyB2ZXJzaW9uPSIxLjEiIGlkPSJMMSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB4bWxuczp4bGluaz0iaHR0cDovL3d3dy53My5vcmcvMTk5OS94bGluayIgeD0iMHB4IiB5PSIwcHgiIHZpZXdCb3g9IjAgMCAxMDAgMTAwIiBlbmFibGUtYmFja2dyb3VuZD0ibmV3IDAgMCAxMDAgMTAwIiB4bWw6c3BhY2U9InByZXNlcnZlIj4KCgogIDxnIGZpbGw9IiNmZmYiPgogIDxyZWN0IHg9IjMwIiB5PSIzNSIgd2lkdGg9IjUiIGhlaWdodD0iMzAiPgogICAgPGFuaW1hdGVUcmFuc2Zvcm0gCiAgICAgICBhdHRyaWJ1dGVOYW1lPSJ0cmFuc2Zvcm0iIAogICAgICAgZHVyPSIxcyIgCiAgICAgICB0eXBlPSJ0cmFuc2xhdGUiIAogICAgICAgdmFsdWVzPSIwIDUgOyAwIC01OyAwIDUiIAogICAgICAgcmVwZWF0Q291bnQ9ImluZGVmaW5pdGUiIAogICAgICAgYmVnaW49IjAuMSIvPgogIDwvcmVjdD4KICA8cmVjdCB4PSI0MCIgeT0iMzUiIHdpZHRoPSI1IiBoZWlnaHQ9IjMwIiA+CiAgICA8YW5pbWF0ZVRyYW5zZm9ybSAKICAgICAgIGF0dHJpYnV0ZU5hbWU9InRyYW5zZm9ybSIgCiAgICAgICBkdXI9IjFzIiAKICAgICAgIHR5cGU9InRyYW5zbGF0ZSIgCiAgICAgICB2YWx1ZXM9IjAgNSA7IDAgLTU7IDAgNSIgCiAgICAgICByZXBlYXRDb3VudD0iaW5kZWZpbml0ZSIgCiAgICAgICBiZWdpbj0iMC4yIi8+CiAgPC9yZWN0PgogIDxyZWN0IHg9IjUwIiB5PSIzNSIgd2lkdGg9IjUiIGhlaWdodD0iMzAiID4KICAgIDxhbmltYXRlVHJhbnNmb3JtIAogICAgICAgYXR0cmlidXRlTmFtZT0idHJhbnNmb3JtIiAKICAgICAgIGR1cj0iMXMiIAogICAgICAgdHlwZT0idHJhbnNsYXRlIiAKICAgICAgIHZhbHVlcz0iMCA1IDsgMCAtNTsgMCA1IiAKICAgICAgIHJlcGVhdENvdW50PSJpbmRlZmluaXRlIiAKICAgICAgIGJlZ2luPSIwLjMiLz4KICA8L3JlY3Q+CiAgPHJlY3QgeD0iNjAiIHk9IjM1IiB3aWR0aD0iNSIgaGVpZ2h0PSIzMCIgPgogICAgPGFuaW1hdGVUcmFuc2Zvcm0gCiAgICAgICBhdHRyaWJ1dGVOYW1lPSJ0cmFuc2Zvcm0iIAogICAgICAgZHVyPSIxcyIgCiAgICAgICB0eXBlPSJ0cmFuc2xhdGUiIAogICAgICAgdmFsdWVzPSIwIDUgOyAwIC01OyAwIDUiICAKICAgICAgIHJlcGVhdENvdW50PSJpbmRlZmluaXRlIiAKICAgICAgIGJlZ2luPSIwLjQiLz4KICA8L3JlY3Q+CiAgPHJlY3QgeD0iNzAiIHk9IjM1IiB3aWR0aD0iNSIgaGVpZ2h0PSIzMCIgPgogICAgPGFuaW1hdGVUcmFuc2Zvcm0gCiAgICAgICBhdHRyaWJ1dGVOYW1lPSJ0cmFuc2Zvcm0iIAogICAgICAgZHVyPSIxcyIgCiAgICAgICB0eXBlPSJ0cmFuc2xhdGUiIAogICAgICAgdmFsdWVzPSIwIDUgOyAwIC01OyAwIDUiIAogICAgICAgcmVwZWF0Q291bnQ9ImluZGVmaW5pdGUiIAogICAgICAgYmVnaW49IjAuNSIvPgogIDwvcmVjdD4KICA8L2c+Cjwvc3ZnPgo=';

const spinnerSVG = chartLoaderSVG;

interface ISpinnerProps {
  size?: number;
  fontSize?: number;
  loadingText?: string;
  horizontalPosition?: string;
  marginTop?: string;
  marginBottom?: string;
}

const DEFAULT_LOADING_TEXT = 'Loading...';

const Spinner = (props: ISpinnerProps) => {
  return (
    <div>
      <span className="loading-image" />
      <p className="loading-text">
        {props.loadingText ? props.loadingText : DEFAULT_LOADING_TEXT}
      </p>
    </div>
  );
};

export default Spinner;
