export const SET_CHART_DATA = 'SET_CHART_DATA';
export const SET_CHART_DATA_LOADING_STATUS = 'SET_CHART_DATA_LOADING_STATUS';
export const SET_CHART_DETAIL_DATA = 'SET_CHART_DETAIL_DATA';
export const SET_CHART_DETAIL_DATA_LOADING_STATUS =
  'SET_CHART_DETAIL_DATA_LOADING_STATUS';
